apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: menty-live-tls
  namespace: default
spec:
  secretName: menty-live-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: menty.live
  dnsNames:
    - menty.live