apiVersion: batch/v1
kind: Job
metadata:
  name: create-kafka-topics
spec:
  template:
    spec:
      containers:
        - name: kafka-topic-creator
          image: bitnami/kafka:3.6.1
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for Kafka to be ready..."
              sleep 30  # Give Kafka time to start
              echo "Creating Kafka topics..."
              KAFKA_CMD="kafka-topics.sh --bootstrap-server kafka-service:9092 --if-not-exists --create --replication-factor 1 --partitions 1 --topic"
              
              $KAFKA_CMD add-student
              # Admin related topics
              $KAFKA_CMD update-admin-wallet
              $KAFKA_CMD create-admin-data
              
              # Student related topics
              $KAFKA_CMD update-password-student
              $KAFKA_CMD update-profile-student
              $KAFKA_CMD block-student
              $KAFKA_CMD password-reset-student
              
              # Instructor related topics
              $KAFKA_CMD update-password-instructor
              $KAFKA_CMD update-profile-instructor
              $KAFKA_CMD block-instructor
              $KAFKA_CMD add-instructor-data
              $KAFKA_CMD update-instructor-wallet
              $KAFKA_CMD password-reset-instructor
              
              # Booking and other topics
              $KAFKA_CMD add-booking
              
              # Email related topics
              $KAFKA_CMD send-otp-email
              $KAFKA_CMD send-forgotPassword-email
              $KAFKA_CMD verified-Instructor-email
              
              echo "Kafka topics created successfully!"
      restartPolicy: Never
  backoffLimit: 4